project_id = "vdxsmqqzjvobgboczeyd"

[functions.farcaster-auth]
verify_jwt = false

[functions.generate-nft-metadata]
verify_jwt = false

[functions.save-to-leaderboard]
verify_jwt = false

[functions.fetch-base-activity]
verify_jwt = false

[functions.update-nft-status]
verify_jwt = false
